# Generated by Django 5.0.7 on 2024-07-13 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AptitudePhysique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', models.BooleanField()),
                ('audition', models.BooleanField()),
                ('mobilite', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Bourgoumestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Officier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDemande', models.DateField()),
                ('etatDemande', models.CharField(max_length=100)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.couple')),
            ],
        ),
        migrations.CreateModel(
            name='Mariage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCelebration', models.DateField()),
                ('lieuCelebration', models.CharField(max_length=100)),
                ('bourgoumestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bourgoumestre')),
                ('couple', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.couple')),
                ('officier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.officier')),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('dateNaissance', models.DateField()),
                ('lieuNaissance', models.CharField(max_length=100)),
                ('nationalite', models.CharField(max_length=100)),
                ('aptitudePhysique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aptitudephysique')),
            ],
        ),
        migrations.AddField(
            model_name='couple',
            name='personne1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personne1', to='app.personne'),
        ),
        migrations.AddField(
            model_name='couple',
            name='personne2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personne2', to='app.personne'),
        ),
        migrations.AddField(
            model_name='officier',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.AddField(
            model_name='bourgoumestre',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
