from .Person import Person
from .User import User
from .Admin import Admin
from .Mayor import Mayor
from .Officer import Officer
from .PhysicalAbility import PhysicalAbility
from .Couple import Couple
from .Request import Request
from .Marriage import Marriage
from .Witness import Witness
