import app.models.Mayor
import app.models.Admin
import app.models.Couple
import app.models.Marriage
import app.models.Officer
import app.models.Person
import app.models.PhysicalAbility
import app.models.Request
import app.models.User
import app.models.Witness
